// This file was auto-generated by Fern from our API Definition.

package paymentmethod

import (
	mercoafinancego "github.com/mercoa-finance/go"
)

type AddAccelerationFundsRequest struct {
	// The amount of the acceleration funds to add. If the entered amount has more decimal places than the currency supports, trailing decimals will be truncated.
	Amount float64 `json:"amount" url:"-"`
	// The currency of the acceleration funds to add.
	Currency mercoafinancego.CurrencyCode `json:"currency" url:"-"`
}

type CompleteMicroDepositsRequest struct {
	// The amounts of the micro deposits in cents
	Amounts []int `json:"amounts,omitempty" url:"-"`
}

type RemoveAccelerationFundsRequest struct {
	// The amount of the acceleration funds to remove. If the entered amount has more decimal places than the currency supports, trailing decimals will be truncated.
	Amount float64 `json:"amount" url:"-"`
	// The currency of the acceleration funds to remove.
	Currency mercoafinancego.CurrencyCode `json:"currency" url:"-"`
}
