// This file was auto-generated by Fern from our API Definition.

package paymentmethod

import (
	mercoafinancego "github.com/mercoa-finance/go"
	time "time"
)

type PaymentMethodEventsRequest struct {
	// Start date filter. If not provided, events from the start of time will be returned.
	StartDate *time.Time `json:"-" url:"startDate,omitempty"`
	// End date filter. If not provided, events to the end of time will be returned.
	EndDate *time.Time `json:"-" url:"endDate,omitempty"`
	// Limit the number of events returned. Limit can range between 1 and 100, and the default is 50.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The ID of the event to start after.
	StartingAfter *mercoafinancego.PaymentMethodEventID `json:"-" url:"startingAfter,omitempty"`
}

type GetAllPaymentMethodsRequest struct {
	// Type of payment method to filter
	Type []*mercoafinancego.PaymentMethodType `json:"-" url:"type,omitempty"`
}

type PlaidLinkTokenRequest struct {
	// ID of Bank Account to update
	PaymentMethodID *mercoafinancego.PaymentMethodID `json:"-" url:"paymentMethodId,omitempty"`
}
