// This file was auto-generated by Fern from our API Definition.

package entity

import (
	json "encoding/json"
	mercoafinancego "github.com/mercoa-finance/go"
)

type BulkEntityCreationRequest struct {
	// If true, webhooks will be emitted for each entity that is created. By default, webhooks are not emitted.
	EmitWebhooks *bool                                      `json:"-" url:"emitWebhooks,omitempty"`
	Body         *mercoafinancego.BulkEntityCreationRequest `json:"-" url:"-"`
}

func (b *BulkEntityCreationRequest) UnmarshalJSON(data []byte) error {
	body := new(mercoafinancego.BulkEntityCreationRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.Body = body
	return nil
}

func (b *BulkEntityCreationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}
