// This file was auto-generated by Fern from our API Definition.

package entity

import (
	json "encoding/json"
	core "github.com/mercoa-finance/go/core"
)

type NumApproverLessThanOneError struct {
	*core.APIError
	Body string
}

func (n *NumApproverLessThanOneError) UnmarshalJSON(data []byte) error {
	var body string
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 400
	n.Body = body
	return nil
}

func (n *NumApproverLessThanOneError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NumApproverLessThanOneError) Unwrap() error {
	return n.APIError
}

type NumApproversUserListMismatchError struct {
	*core.APIError
	Body string
}

func (n *NumApproversUserListMismatchError) UnmarshalJSON(data []byte) error {
	var body string
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 400
	n.Body = body
	return nil
}

func (n *NumApproversUserListMismatchError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NumApproversUserListMismatchError) Unwrap() error {
	return n.APIError
}
