// This file was auto-generated by Fern from our API Definition.

package entity

import (
	mercoafinancego "github.com/mercoa-finance/go"
)

type CompleteMicroDepositsRequest struct {
	Amounts []int `json:"amounts,omitempty" url:"amounts,omitempty"`
}

type GetAllPaymentMethodsRequest struct {
	// Type of payment method to filter
	Type []*mercoafinancego.PaymentMethodType `json:"-" url:"type,omitempty"`
}
