// This file was auto-generated by Fern from our API Definition.

package entitygroup

import (
	mercoafinancego "github.com/mercoa-finance/go"
	time "time"
)

type GroupInvoiceDownloadRequest struct {
	// Format of the file to download. Defaults to CSV.
	Format *mercoafinancego.BulkDownloadFormat `json:"-" url:"format,omitempty"`
	// Start date filter. Defaults to CREATED_AT unless specified the dateType is specified
	StartDate *time.Time `json:"-" url:"startDate,omitempty"`
	// End date filter. Defaults to CREATED_AT unless specified the dateType is specified
	EndDate *time.Time `json:"-" url:"endDate,omitempty"`
	// Type of date to filter by if startDate and endDate filters are provided. Defaults to CREATED_AT.
	DateType *mercoafinancego.InvoiceDateFilter `json:"-" url:"dateType,omitempty"`
	// Field to order invoices by. Defaults to CREATED_AT.
	OrderBy *mercoafinancego.InvoiceOrderByField `json:"-" url:"orderBy,omitempty"`
	// Direction to order invoices by. Defaults to asc.
	OrderDirection *mercoafinancego.OrderDirection `json:"-" url:"orderDirection,omitempty"`
	// Find invoices by vendor name, invoice number, check number, or amount. Partial matches are supported.
	Search *string `json:"-" url:"search,omitempty"`
	// Filter invoices by metadata. Each filter will be applied as an AND condition. Duplicate keys will be ignored.
	Metadata []*mercoafinancego.MetadataFilter `json:"-" url:"metadata,omitempty"`
	// Filter invoices by line item metadata. Each filter will be applied as an AND condition. Duplicate keys will be ignored.
	LineItemMetadata []*mercoafinancego.MetadataFilter `json:"-" url:"lineItemMetadata,omitempty"`
	// Filter invoices by line item GL account ID. Each filter will be applied as an OR condition. Duplicate keys will be ignored.
	LineItemGlAccountID []*string `json:"-" url:"lineItemGlAccountId,omitempty"`
	// Filter invoices by payer ID or payer foreign ID.
	PayerID []*mercoafinancego.EntityID `json:"-" url:"payerId,omitempty"`
	// Filter invoices by vendor ID or vendor foreign ID.
	VendorID []*mercoafinancego.EntityID `json:"-" url:"vendorId,omitempty"`
	// Filter invoices by the ID or foreign ID of the user that created the invoice.
	CreatorUserID []*mercoafinancego.EntityUserID `json:"-" url:"creatorUserId,omitempty"`
	// Filter invoices by assigned approver user ID. Only invoices with all upstream policies approved will be returned.
	ApproverID []*mercoafinancego.EntityUserID `json:"-" url:"approverId,omitempty"`
	// Filter invoices by approver action. Needs to be used with approverId. For example, if you want to find all invoices that have been approved by a specific user, you would use approverId and approverAction=APPROVE.
	ApproverAction []*mercoafinancego.ApproverAction `json:"-" url:"approverAction,omitempty"`
	// Filter invoices by invoice ID or invoice foreign ID.
	InvoiceID []*mercoafinancego.InvoiceID `json:"-" url:"invoiceId,omitempty"`
	// Invoice status to filter on
	Status []*mercoafinancego.InvoiceStatus `json:"-" url:"status,omitempty"`
	// Filter invoices by recurring status
	PaymentType []mercoafinancego.PaymentType `json:"-" url:"paymentType,omitempty"`
	// Filter invoice by invoice template ID
	InvoiceTemplateID []*mercoafinancego.InvoiceTemplateID `json:"-" url:"invoiceTemplateId,omitempty"`
	// Return only invoices that are receivable by the entity.
	ExcludePayables *bool `json:"-" url:"excludePayables,omitempty"`
	// Return only invoices that are payable by the entity.
	ExcludeReceivables *bool `json:"-" url:"excludeReceivables,omitempty"`
	// Whether to return payer metadata in the response
	ReturnPayerMetadata *bool `json:"-" url:"returnPayerMetadata,omitempty"`
	// Whether to return vendor metadata in the response
	ReturnVendorMetadata *bool `json:"-" url:"returnVendorMetadata,omitempty"`
}

type EntityGetInvoicesRequest struct {
	// Return only invoices that are receivable by the entity.
	ExcludePayables *bool `json:"-" url:"excludePayables,omitempty"`
	// Return only invoices that are payable by the entity.
	ExcludeReceivables *bool `json:"-" url:"excludeReceivables,omitempty"`
	// Start date for invoice created on date filter.
	StartDate *time.Time `json:"-" url:"startDate,omitempty"`
	// End date for invoice created date filter.
	EndDate *time.Time `json:"-" url:"endDate,omitempty"`
	// Type of date to filter by if startDate and endDate filters are provided. Defaults to CREATED_AT.
	DateType *mercoafinancego.InvoiceDateFilter `json:"-" url:"dateType,omitempty"`
	// Field to order invoices by. Defaults to CREATED_AT.
	OrderBy *mercoafinancego.InvoiceOrderByField `json:"-" url:"orderBy,omitempty"`
	// Direction to order invoices by. Defaults to asc.
	OrderDirection *mercoafinancego.OrderDirection `json:"-" url:"orderDirection,omitempty"`
	// Number of invoices to return. Limit can range between 1 and 100, and the default is 10.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The ID of the invoice to start after. If not provided, the first page of invoices will be returned.
	StartingAfter *mercoafinancego.InvoiceID `json:"-" url:"startingAfter,omitempty"`
	// Filter invoices by metadata. Each filter will be applied as an AND condition. Duplicate keys will be ignored.
	Metadata []*mercoafinancego.MetadataFilter `json:"-" url:"metadata,omitempty"`
	// Find invoices by vendor name, invoice number, check number, or amount. Partial matches are supported.
	Search *string `json:"-" url:"search,omitempty"`
	// Filter invoices by payer ID or payer foreign ID.
	PayerID []*mercoafinancego.EntityID `json:"-" url:"payerId,omitempty"`
	// Filter invoices by vendor ID or vendor foreign ID.
	VendorID []*mercoafinancego.EntityID `json:"-" url:"vendorId,omitempty"`
	// Filter invoices by the ID or foreign ID of the user that created the invoice.
	CreatorUserID []*mercoafinancego.EntityUserID `json:"-" url:"creatorUserId,omitempty"`
	// Filter invoices by assigned approver user ID.
	ApproverID []*mercoafinancego.EntityUserID `json:"-" url:"approverId,omitempty"`
	// Filter invoices by approver action. Needs to be used with approverId. For example, if you want to find all invoices that have been approved by a specific user, you would use approverId and approverAction=APPROVE.
	ApproverAction []*mercoafinancego.ApproverAction `json:"-" url:"approverAction,omitempty"`
	// Filter invoices by the number of approvers. Use exact number (e.g., 3) or range (e.g., ">3", "<5", ">=2", "<=4").
	ApproverCount *string `json:"-" url:"approverCount,omitempty"`
	// Filter invoices by invoice ID or invoice foreign ID.
	InvoiceID []*mercoafinancego.InvoiceID `json:"-" url:"invoiceId,omitempty"`
	// Invoice status to filter on.
	Status []*mercoafinancego.InvoiceStatus `json:"-" url:"status,omitempty"`
	// Filter invoices by recurring status
	PaymentType []mercoafinancego.PaymentType `json:"-" url:"paymentType,omitempty"`
	// Whether to return payer metadata in the response
	ReturnPayerMetadata *bool `json:"-" url:"returnPayerMetadata,omitempty"`
	// Whether to return vendor metadata in the response
	ReturnVendorMetadata *bool `json:"-" url:"returnVendorMetadata,omitempty"`
	// Whether to return payment timing in the response
	ReturnPaymentTiming *bool `json:"-" url:"returnPaymentTiming,omitempty"`
}

type GroupInvoiceMetricsRequest struct {
	// Find invoices by vendor name, invoice number, check number, or amount. Partial matches are supported.
	Search *string `json:"-" url:"search,omitempty"`
	// Only return invoices that are not payable by the entity. This will return only invoices that are receivable by the entity.
	ExcludePayables *bool `json:"-" url:"excludePayables,omitempty"`
	// Only return invoices that are not receivable by the entity. This will return only invoices that are payable by the entity.
	ExcludeReceivables *bool `json:"-" url:"excludeReceivables,omitempty"`
	// Return invoice metrics grouped by date.
	ReturnByDate *mercoafinancego.InvoiceMetricsPerDateGroupBy `json:"-" url:"returnByDate,omitempty"`
	// Return invoice metrics grouped by date. Defaults to daily.
	ReturnByDateFrequency *mercoafinancego.InvoiceMetricsPerDateFrequency `json:"-" url:"returnByDateFrequency,omitempty"`
	// Return invoice metrics grouped by.
	GroupBy []*mercoafinancego.InvoiceMetricsGroupBy `json:"-" url:"groupBy,omitempty"`
	// Filter invoices by payer ID.
	PayerID []*mercoafinancego.EntityID `json:"-" url:"payerId,omitempty"`
	// Filter invoices by vendor ID.
	VendorID []*mercoafinancego.EntityID `json:"-" url:"vendorId,omitempty"`
	// Filter invoices by assigned approver user ID.
	ApproverID []*mercoafinancego.EntityUserID `json:"-" url:"approverId,omitempty"`
	// Filter invoices by the number of approvers. Use exact number (e.g., 3) or range (e.g., ">3", "<5", ">=2", "<=4").
	ApproverCount *string `json:"-" url:"approverCount,omitempty"`
	// Filter invoices by invoice ID or invoice foreign ID.
	InvoiceID []*mercoafinancego.InvoiceID `json:"-" url:"invoiceId,omitempty"`
	// Invoice status to filter on
	Status []*mercoafinancego.InvoiceStatus `json:"-" url:"status,omitempty"`
	// Start date filter. Defaults to CREATED_AT unless specified the dateType is specified
	StartDate *time.Time `json:"-" url:"startDate,omitempty"`
	// End date filter. Defaults to CREATED_AT unless specified the dateType is specified
	EndDate *time.Time `json:"-" url:"endDate,omitempty"`
	// Type of date to filter by if startDate and endDate filters are provided. Defaults to CREATED_AT.
	DateType *mercoafinancego.InvoiceDateFilter `json:"-" url:"dateType,omitempty"`
	// Currency to filter on
	Currency []*mercoafinancego.CurrencyCode `json:"-" url:"currency,omitempty"`
}
